### ISSUE TITLE
how to invoke the .vue files

### ISSUE THREAD

**Issue by balajijana** [eliep/vue-avatar#1]
Hi,
I am working angular 2 application.
I used this module as per the document: 

1.npm install vue-avatar

2. In the .ts file I have called this statement:

import Avatar from 'vue-avatar/dist/Avatar'

export default {

  components: {
    Avatar
  },
}

when i try to run the application i got the error as :  http://localhost:3001/node_modules/vue-avatar/dist/Avatar.js 404 (Not Found)

Please let  me know how to call the .vue file or what is wrong here?

**Comment by balajijana** [comment]
Does this module supports for typescript?

**Comment by eliep** [comment]
Hi balajijana,

When you import this component via 
```
import Avatar from 'vue-avatar/dist/Avatar'
```
it will use the .vue file.
