### ISSUE TITLE
Interpolation inside attributes has been removed in Vue.js v2.2.4

### ISSUE THREAD

**Issue by danhellem** [eliep/vue-avatar#10]
`<avatar` username="{{profile.firstName}}" :size="128"></avatar>

get the following error:

`username="{{profile.firstName}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.`

Change to `<avatar` :username="profile.firstName" :size="128"></avatar> 

```
[Vue warn]: Invalid prop: type check failed for prop "username". Expected String, got Undefined. 
(found in <Avatar>)
```

**Comment by danhellem** [comment]
found a work around

**Comment by weislanes** [comment]
What's the workaround?

**Comment by ssuess** [comment]
yes please what is the workaround??
