### ISSUE TITLE
Inline block for avatar

### ISSUE THREAD

**Issue by fizerkhan** [eliep/vue-avatar#11]
Most of the time, avatar will be followed by full name. Since the avatar has `div` element, it pushes the name text to the next line. Can you make avatar as `inline-block` by default? Otherwise can you provide a props to do it?

**Comment by saintplay** [comment]
**Version** 2.1.1; You can add custom styles 

```html
<avatar username="Hubert-Félix Thiéfaine" :customStyle="{ 'display´: 'inline-block'}"></avatar>
```

**Comment by fizerkhan** [comment]
@saintplay Thanks. 👍

**Comment by mattgrande** [comment]
Is there a way I can set a default custom style throughout my whole site? Or would I be better off creating a wrapper component, and using that everywhere?

**Comment by saintplay** [comment]
You can customize the `.vue-avatar--wrapper` class like 

```css
.vue-avatar--wrapper {
  display: inline-block !important;
}
```
