### ISSUE TITLE
@avatar-initials event

### ISSUE THREAD

**Issue by czytelny** [eliep/vue-avatar#12]
Hi, I'm dynamically building initials based on user input's name and would like to use `@avatar-initials` event to synchronize it with vuex state. Unfortunately as I can see in the source  this event is emitted only on `mounted ()` lifecycle phase. Would you mind if I create PR for firing this event every time initials are updated ? (https://github.com/eliep/vue-avatar/pull/13)

**Comment by saintplay** [comment]
closed due inactivity.

Please reopen if you need this.
Maybe I will implement a` @change` event
