### ISSUE TITLE
[Bug] Missing background styling after dynamically updating the 'src' property

### ISSUE THREAD

**Issue by egyptik** [eliep/vue-avatar#14]
On initial rendering, the avatar property adds the following CSS when the 'src' property is set:

`background: url("src_path") 0% 0% / 100px 100px no-repeat content-box;`

However, if the 'src' property is bound to a computed element, which then gets updated after the initial rendering of the avatar element, the CSS background property gets updated to:

`background: url("src_path");`

Missing `0% 0% / 100px 100px no-repeat content-box;` and causing the image to be displayed incorrectly.

**Comment by LTroya** [comment]
Hi,

Did you find a workaround for this? 

Two options came to my mind:
1 - Fork this project and change the component
2 - Use a `img` tag when there is a photo, this is my current workaround for the time being

**Comment by rmartins90** [comment]
+1

**Comment by egyptik** [comment]
I fixed it by making a sort of 'wrapper' component since I also needed it to show an image in most cases, but with a fallback to a letter avatar when no image src is provided or when the src url returns a 404. So similar to option 2!

**Comment by rmartins90** [comment]
https://github.com/eliep/vue-avatar/pull/9

**Comment by alekbarszczewski** [comment]
Guys what is going on - is this project abandoned or what?

**Comment by egyptik** [comment]
Seems like it
