### ISSUE TITLE
Attribute "username" is ignored on component <avatar> because the component is a fragment instance

### ISSUE THREAD

**Issue by lukpep** [eliep/vue-avatar#2]
vue.js version 1.0.24

JS:
`import Avatar from 'vue-avatar'`

```
components: {
      Avatar
    },
```

html:
`<avatar username="Jane Doe"></avatar>`

**Comment by eliep** [comment]
Hi lukpep,

I'm not sure the <avatar> component is a fragment instance, because it has a single root-level element.

In your case, the import might be the problem. Can you try

```
import Avatar from 'vue-avatar/dist/Avatar'

components: {
  Avatar
},
```
or
```
import Avatar from 'vue-avatar'

components: {
  'avatar': Avatar.Avatar
},
```

**Comment by lukpep** [comment]
```
components: {
  'avatar': Avatar.Avatar
},
```

works fine. Thanks for Your help :)
