### ISSUE TITLE
Runtime-only build of Vue/Precompiled Templates

### ISSUE THREAD

**Issue by seanwash** [eliep/vue-avatar#21]
Hello, I'm using vue-avatar within my Nuxt project (@nuxt) and get this error on render:

[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

It works if I reference the compiler-included build in the web pack configuration of Nuxt like this:

```
build: { extend(config) { config.resolve.alias['vue'] = 'vue/dist/vue.common' } }
```

Is there another work-around? Like pre-compiling templates on build? I'd be happy to work on a PR.

**Comment by saintplay** [comment]
You can import the **.vue** file directly like this:

```js
import Avatar from 'vue-avatar/dist/Avatar';
```
But this only works with the right build config..

So, I'm waiting #17 to be merged

**Comment by saintplay** [comment]
Now **vue-avatar** can be imported like this:

```js
import Avatar from 'vue-avatar';
```
