### ISSUE TITLE
Doesn't work with vue-cli pwa template

### ISSUE THREAD

**Issue by jeppe-smith** [eliep/vue-avatar#23]
The template uses babel-env but when importing 'vue-avatar/dist/Avatar' I get "Module build failed: Error: Couldn't find preset "es2015" relative to directory". Solved it by installing the babel-preset-es2015 but it would be nice if it wasn't dependent on that.

**Comment by saintplay** [comment]
The build process was updated, now **vue-avatar** can be imported like this:

```js
import Avatar from 'vue-avatar'
```

**Version**: 2.1.0
