### ISSUE TITLE
Avatar show with 0x0 pixel size 

### ISSUE THREAD

**Issue by wasinr** [eliep/vue-avatar#26]
Hi, i'm using vue-avatar on nuxtjs project, I have install avatar to my project and put in on the page/index.vue

`<avatar username="Jane Doe" :size="100"></avatar>`

When I try to run the project I got 0x0 pixel avatar and if I inspect the html, I saw jut

`<avatar username="Jane Doe" size="100" data-v-2a183b29=""></avatar>`

any idea how to fix?

**Comment by saintplay** [comment]
Hi,
what is the component version you are using?

**Comment by saintplay** [comment]
closed due inactivity
