### ISSUE TITLE
Update picture or initials without refresh the page

### ISSUE THREAD

**Issue by vitalibr** [eliep/vue-avatar#28]
Am I doing something wrong or changing the image path and not changing a picture on vue-avatar?

**Comment by saintplay** [comment]
I just tested this, and couldn't replicate the error. Can you show code or create a minimal replication in a [codesandbox](https://codesandbox.io/s/vue) please

**Comment by saintplay** [comment]
Closed due inactivity, @anyone feel free to reopen
