### ISSUE TITLE
Initials letters not in the middle

### ISSUE THREAD

**Issue by e200** [eliep/vue-avatar#31]
Avatar letters not well vertically aligned to the center, check: https://eliep.github.io/vue-avatar

**Comment by saintplay** [comment]
Hi, can you provide a screenshot?

**Comment by e200** [comment]
mtp://[usb:002,027]/Phone/DCIM/Screenshots/Screenshot_20180412-111521.png

**Comment by e200** [comment]
![screenshot_20180412-111521](https://user-images.githubusercontent.com/20504726/38671335-09472150-3e43-11e8-8176-1cb78045e0d9.png)

**Comment by e200** [comment]
Samsung Galaxy s6 (Firefox)

**Comment by saintplay** [comment]
yeah, I should apply flexbox instead for proper centering

**Comment by saintplay** [comment]
Actually, `line-height` is perfect, it only needs a small adjustment.

https://codepen.io/chriscoyier/pen/LxHmK

can you make a PR?

**Comment by e200** [comment]
Of course.
