### ISSUE TITLE
Strange avatar text position

### ISSUE THREAD

**Issue by galczo5** [eliep/vue-avatar#41]
Hi.
Text content position is very strange.
![image](https://user-images.githubusercontent.com/6080725/48546736-64157b00-e8c9-11e8-9949-557591f7bb8c.png)

I found out that this is related to:
https://github.com/eliep/vue-avatar/blob/master/src/Avatar.vue#L97

Line height is set to `100px`, and I think that it should be set to `this.size`.
I'll prepare PR later today.

**Comment by galczo5** [comment]
https://github.com/eliep/vue-avatar/pull/42

**Comment by galczo5** [comment]
@eliep Any chances to resolve it quick?

**Comment by xShivan** [comment]
Please, merge the bugfix for this issue.

**Comment by saintplay** [comment]
Available in npm: **v2.1.7**

**Comment by xShivan** [comment]
Thank you!
