### ISSUE TITLE
Custom parser

### ISSUE THREAD

**Issue by andreasvirkus** [eliep/vue-avatar#44]
Hi there!

First off, thanks for a great component : ) It's a go-to default for most of my projects 💯 

Currently, when a passed in name contains parenthesis (e.g. `James (Team lead)`), the displayed avatar is `J(L`. Would you be willing to exclude/filter out parenthesis before performing the lookup for the initials? Or a prop which would allow the user to completely ignore the contents of the parenthesis (so either `JTL` or `J` would get displayed).

Here's a short repro: https://codesandbox.io/s/1qx82p6k7q

Would be willing to look into it as well, if you're open to contributions

Best,
andreas

**Comment by saintplay** [comment]
Hi!
Thanks for the detailed issue.
Glad you find helpful this component!

This is a interesting use case though, I don't think we should add this directly to the component.

The **prop** sounds like a good idea, but you know, many people could possibly need the same abstraction in other forms

- James Romney (Team Lead) (*how to exclude "(Team Lead)"?*)
- James Romney - Team Lead(*how to exclude "- Team Lead"?*)
- { "name:" "James Romney", "role": "Team Lead" }(*how to parse an object"?*)
- Dr. James Romney (*how to exclude "dr"?*)
- and many many more

We can't support all these use cases at the same time

The best workaround is pre formatting the string before passing through the prop.

```js
var username =  "James Romney (Team Lead)"
var formattedUsername = formatUsername(username) // James Romney

<vue-avatar :username="formattedUsername"></vue-avatar>
```

However I like the idea of provide a **prop to change the default parser**, like this:

```js
<vue-avatar :username="username" :parser="formatUsername"></vue-avatar>
```

What do you think?

Regards

**Comment by andreasvirkus** [comment]
I'd like to take this issue on; I'll have a look tomorrow night! ✊
