### ISSUE TITLE
How to use the customStyle property

### ISSUE THREAD

**Issue by Tarabass** [eliep/vue-avatar#62]
For now the size accepts only numbers. I want to be able to use `7vw` instead of `70px`. My idea was to use this:

`:customStyle="{ height: '7vw !important;', width: '7vw !important;' }"`

But it doesn't work :(

**Comment by kasnti** [comment]
`:customStyle="vueAvatar.styleObject"`

```
data() {
    return {
      vueAvatar: {
        styleObject: {
          height: '7vw !important;'
          width: '7vw !important;'
        },
      }
    }
  }
```

**Comment by Tarabass** [comment]
@kasnti That would result in exactly the same thing. But while I was trying your code I noticed that the problem was within my own code.

If I remove the __semicolons__ it works. This is how Vue is expecting it and what I did wrong.
```javascript
<avatar :customStyle="{ height: '7vw', width: '7vw' }" username="Jane Doe"></avatar>
```

**Comment by kasnti** [comment]
@Tarabass you are right

**Comment by Tarabass** [comment]
Thank you for pointing me into the right direction 😝
