### ISSUE TITLE
bind a variable to username

### ISSUE THREAD

**Issue by wowmelo** [eliep/vue-avatar#67]
I tried 

`  <avatar
                     :rounded="false"
                     :size="100" class="picture card border-white rounded shadow" :username="data.name"></avatar>
`

but it does not work.
how to solve this?

**Comment by saintplay** [comment]
I'm sorry but this is clearly not a vue-avatar problem. I suggest you to search for help in vue discord or stackoverflow

**Comment by Kharismatics** [comment]
Try this v-bind:username="data.name"
