### ISSUE TITLE
Avatar is not updated when change from unavailable src to available src 

### ISSUE THREAD

**Issue by ppzzppz** [eliep/vue-avatar#71]
Avatar is not updated when change from unavailable src to available src 

![image](https://user-images.githubusercontent.com/34941345/88289526-6b2f9600-cd06-11ea-81cb-ebd267e9b109.png)

temporally resolve  as below

![image](https://user-images.githubusercontent.com/34941345/88289730-bf3a7a80-cd06-11ea-85af-a77d06b5777e.png)

**Comment by ppzzppz** [comment]
Do you need pr ?

**Comment by saintplay** [comment]
Interesting, a PR would be fine, thanks

**Comment by ppzzppz** [comment]
Review welcome
