### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by mits87** [eliep/vue-avatar#77]
Hi, 

is it possible to add support for Vue3 ?

Thanks!

**Comment by saintplay** [comment]
Hi, I still didn't check Vue 3 documentation (breaking changes, new API, etc).

Did you tried to use this with vue 3 and didn't work?

**Comment by mits87** [comment]
@saintplay no it doesn't work. I think the vue 3 API is different. Right now I have those errors:
https://www.dropbox.com/s/sdd2yv0j6g33fef/Screenshot%202020-10-03%20at%2018.51.41.png?dl=0

**Comment by mits87** [comment]
@saintplay some update here ?

**Comment by saintplay** [comment]
It seems like there is no breaking change for Vue Avatar, however somehow the build is broken for Vue 3.
While this maybe don't have an easy or fast fix you can use the component directly like [this](https://codesandbox.io/s/practical-breeze-93jm5?file=/src/components/HelloWorld.vue)

**Comment by mits87** [comment]
@saintplay actually Vue 3 has breaking changes. 
For instance the composition API etc. 

So I think it should be a different version of vue-avatar dedicated for Vue3.

**Comment by saintplay** [comment]
Resolved in #79
