### ISSUE TITLE
Improve accessibility of avatar component

### ISSUE THREAD

**Issue by pascalwengerter** [eliep/vue-avatar#87]
I've come across two problems with the `vue-avatar` component when trying to make my employer's web application meet accessibility (A11Y) requirements:

1. The wrapping tag is a `<div>`, which is somewhat limited in its usage. We're wrapping the avatar and username in a `<button>` to open a user menu dropdown (common behaviour on other websites), but a `<div>` inside a `<button>` is not valid HTML5 (discussion with more resources can be found [in this thread](https://stackoverflow.com/questions/12982269/is-it-semantically-incorrect-to-put-a-div-or-span-inside-of-a-button/48383389)). I've tried replacing the `<div>` with a `<span>` which is allowed inside a `<button>` and the results looked somewhat the same, so the fix for this should be quick & easy
2. The contrast between background-color and text-color aren't high enough - their contrast ratio is between 1.53 and 3.8 (from what I've seen), whilst accessibility criteria for colorblind/visually impaired people ask for a contrast ratio of >4.5. This can be fixed quite easily by updating the available color/background-color combinations by ones that pass a [color contrast checker](https://webaim.org/resources/contrastchecker/)

Towards the maintainers of this component: Happy to hear your thoughts and please let me know if opening a PR to resolve the two points from my side is worth the effort 🤓

**Comment by saintplay** [comment]
Thanks for bringing this up 😀

1. Sure, we can use spans, but to not break styles it should be display:block by default.
2. This is a good idea. PRs welcomed!

**Comment by pascalwengerter** [comment]
> Thanks for bringing this up 😀
> 
>     1. Sure, we can use spans, but to not break styles it should be display:block by default.
> 
>     2. This is a good idea. PRs welcomed!

Hey @saintplay, I'd start working on this if you give me a go (just making sure it's worth the effort since activity in the repo is rather stagnant and the last build according to the README fails ;) you also hinted towards dropping support for profile pictures, we could also tackle it in one go and go for a major release?). Fully agree with the `display: block` for the spans to keep it stable/backwards-compatible

**Comment by saintplay** [comment]
Sounds good.

I'm not completely sure about dropping support for pictures anymore though, this component would bring too little to the table without it.

**Comment by pascalwengerter** [comment]
Closing here due to inactivity (no offense meant, reasonable response by the maintainer received ;) )
