### ISSUE TITLE
Using vue-avatar in vue 3

### ISSUE THREAD

**Issue by Ifriqiya** [eliep/vue-avatar#90]
Hi, I'm trying to use the vue-avatar in vue 3. Everything seems to check out except that the avatar doesn't display but I can see the name bound to the div element in the console.  If it should work in vue 3, could the problem be my usage? Thanks

**Comment by palmtown** [comment]
Hello,

I'm having a similar issue, however, it simply doesn't work and generates numerous errors.  Any scheduled update to support Vue 3?

**Comment by palmtown** [comment]
Just an F.Y.I., a quick search online and I've found https://www.npmjs.com/package/vue3-avatar?activeTab=versions for others that need a v3 solution.  The author states it's "this component is highly inspired from vue-avatar."  

I tested it and it works with vue 3.

**Comment by Ifriqiya** [comment]
Thanks for the information.
